version: '3.8'

services:
  postgres:
    image: postgres:14-alpine3.20
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ~/data/postgre/persistence:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
    driver: local