version: '3.8'

services:
  db:
    image: mysql:9.2.0-oracle
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ~/data/mysql/persistence:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8081:8081"
    depends_on:
      - db